version: "2"
services:
  db:
    image: mysql:5.7
    container_name: omeka_db
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword #FIXME
      MYSQL_DATABASE: secretstring #FIXME
      MYSQL_USER: secretstring #FIXME
      MYSQL_PASSWORD: secretstring #FIXME

  omeka:
    depends_on:
      - db
    container_name: omekas
    image: omeka
    build:
      context: .
    restart: always
    ports:
      - "8080:80"
    links:
      - db:db
    volumes:
      - omeka:/var/www/html/volume
      - ./database.ini:/var/www/html/config/database.ini
      - ./bootstrap:/var/www/html/themes/bootstrap
      - ./images:/home/images

volumes:
  db:
  omeka:
